[workspace]
resolver = "3"
members = ["alkahest", "alkahest-*"]

[workspace.package]
authors = ["Azoth Foundation <contact@azoth.org>"]
edition = "2024"

[workspace.dependencies]
alkahest-modules = { path = "alkahest-modules" }
alkahest-parser = { path = "alkahest-parser" }
alkahest-lexer = { path = "alkahest-lexer" }