[package]
name = "alkahest-internal"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
license-file = { workspace = true }

[dependencies]
