name: Beta Test (Rust/Cargo)

on:
  push:
    branches: ["beta"]
  pull_request:
    branches: ["beta"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run Cargo Check
        run: cargo check --all-targets --verbose
      - name: Run Cargo Tests
        run: cargo test --all --verbose
